### ISSUE TITLE
add global buffer to store UTXO

### ISSUE THREAD

**Issue by lhfbc** [wunder3605/iri#198]
Now we have a global structure: Transaction, and it may be known as 'blockchain' as it stores all the history of transactions. 
 when we want to find an unspent TransactionOut, we need to search the matching TransactionsOut one by one in the global 'Transaction'  and check it in All TransactionIn in 'Transaction' . The time is O(n^2).

We may have a global buffer to store all UTXOs, and when transferring, we can search the match utxo in the buffer. The time will be O(n).

**Comment by stplaydog** [comment]
I am pretty glad that you can explore and get the point by yourself!
Please think deeper before start typing code.

**Comment by stplaydog** [comment]
#246

duplicate
