### ISSUE TITLE
TX transfer bug

### ISSUE THREAD

**Issue by stplaydog** [wunder3605/iri#207]
When TX request gets to Node A, it will be constructed as a TransactionViewModel then be broadcasted to Node B. When node B accept it, it will call store() which will transfer the format of TransactionViewModel into the UTXO format, but the Hash would not be updated accordingly. 
This TransactionViewModel will be broadcasted back to A, this TransactionViewModel because of its hash would not be updated, will in turn randomly 1) be accepted by A, 2) or be recognized as invalid hash which will result in problems.

The root problem is that, we have embeded the transaction logic (control logic) in the persistence layer (model logic). Should move this part of logic away.

**Comment by wmmair** [comment]
We must update the hash at any time:) and make sure it's right.
